"""init agents table

Revision ID: 1e50b8c48ca1
Revises: 
Create Date: 2025-07-14 01:56:41.700504

"""
from alembic import op
import sqlalchemy as sa
from agents.agent_model import AgentModel, Base
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from config.settings import SQLALCHEMY_DATABASE_URL


# revision identifiers, used by Alembic.
revision = '1e50b8c48ca1'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents')
    # ### end Alembic commands ### 


engine = create_engine(SQLALCHEMY_DATABASE_URL)
Session = sessionmaker(bind=engine)
session = Session()

agents = [
    AgentModel(name='主协调者', type='coordinator', description='全局任务协调', config={}, enabled=True),
    AgentModel(name='AI趋势研究', type='research', description='专注AI领域', config={"domain": "AI"}, enabled=True),
    AgentModel(name='金融分析', type='analysis', description='金融数据分析', config={"domain": "finance"}, enabled=True),
    AgentModel(name='工具调用', type='tool', description='外部API集成', config={"api_key": "xxx"}, enabled=True),
]

session.add_all(agents)
session.commit()
session.close()
print("测试数据已插入！") 